layout_spectrum: 0.4121864
color:
  saturation: 0.9203963
  brandStrength: 0.2289513
  lightness: 0.3244494
  brandColors:
    - '#E1DED9'
    - '#FFFFFF'
    - '#9A8A98'
    - '#A4BEBB'
    - '#552E49'
  rhythmicContrast: 0.8340882
typography_spectrum: 0.5376344
name: Stitchstudio
